# provision/setup/tasks/main.yml

- name: Install packages
  become: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    # Database
    - postgresql
    - libpq-dev # Required for Ansible to interact with PGSQL
    - python3-psycopg2 # "
    #- python-psycopg2

    # Python Dev
    - python3-dev
    - python-setuptools
    - python-virtualenv

    # Python 3
    - python3.4

# called when the above pg_hba.conf file changes
- name: Restart Postgres
  become: yes
  service: name=postgresql state=restarted

- name: Allow password authentication for local socket users
  become: yes
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf force=yes
  notify:
    - Restart Postgres

- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db: name={{ db_name }}

- name: Create User
  become: yes
  become_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} state=present role_attr_flags=NOSUPERUSER,CREATEDB

- name: Provide user with DB permissions
  become: yes
  become_user: postgres
  postgresql_user: name={{ db_user }} db={{ db_name }} priv=ALL